# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.5.8/c2cciutils/schema.json

checks:
  prettier: false
  codespell: false

publish:
  pypi:
    packages: []
  docker:
    dispatch: {}
    images:
      - name: camptocamp/geo_saas
